/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-03 11:38:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Utility.DBConnection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class AdminDailyPrice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("Utility.DBConnection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <title>Market </title>\n");
      out.write("\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    \n");
      out.write("     ");

		DBConnection db = new DBConnection();
        Connection con = db.createConnection();
        
		Statement statement = con.createStatement();
		ResultSet resultSet = null;
		ResultSet resultSetmarket = null;
		Statement statementmarket = con.createStatement();

      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"w3-top\">\n");
      out.write("  <div class=\"w3-bar w3-black w3-wide w3-padding w3-card\">\n");
      out.write("    <a href=\"#home\" class=\"w3-bar-item w3-button\"><b>AG</b> Agro</a>\n");
      out.write("    <!-- Float links to the right. Hide them on small screens -->\n");
      out.write("    <div class=\"w3-right w3-hide-small\">\n");
      out.write("      <a href=\"#products\" class=\"w3-bar-item w3-button\">Products</a>\n");
      out.write("      <a href=\"#about\" class=\"w3-bar-item w3-button\">About</a>\n");
      out.write("      <a href=\"#slideshow\" class=\"w3-bar-item w3-button\">Contact</a>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("     <div class=\"jumbotron jumbotron-fluid\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <h1>Daily Vegetable Price </h1>      \n");
      out.write("            <p> Add the buying and selling price  of the products from a specific market..</p>\n");
      out.write("        </div>\n");
      out.write("    </div>  \n");
      out.write("\n");
      out.write("        <div class=\"container\" >\n");
      out.write("\n");
      out.write("            <button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" \n");
      out.write("            data-target=\"#myModal\">ADD DAILY PRICE</button>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Modal starts here -->\n");
      out.write("    <!--     -->\n");
      out.write("    \n");
      out.write("            <div id=\"myModal\" class=\"modal fade\" role=\"dialog\">\n");
      out.write("                <div class=\"modal-dialog\">\n");
      out.write("\n");
      out.write("    <!-- l content-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                    <h4 class=\"modal-title\">Add the prices:</h4>\n");
      out.write("                    </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <form  action=\"AddDailyPriceServlet\" method=\"post\" >\n");
      out.write("\n");
      out.write("\tEnter the market's name:\n");
      out.write("\t<br>\n");
      out.write("\t <select class=\"form-control\" name =\"DailyMarketName\">\n");
      out.write("\t \n");
      out.write("\t \t<option value=\"-1\">Select Market</option>\n");
      out.write("\t \t\n");
      out.write("\t \t");

			try{ 
				
				String sql ="SELECT * FROM market";

				resultSet = statement.executeQuery(sql);
		
 
				while(resultSet.next()){
		
      out.write("\n");
      out.write("\t\t\t<option>");
      out.print(resultSet.getString(3) );
      out.write("</option>\n");
      out.write("    \t");
 
		}

		} catch (Exception e) {
			e.printStackTrace();
		}
		
      out.write("\n");
      out.write("\t\n");
      out.write("\t </select>\n");
      out.write("\t\n");
      out.write("\t<br>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\tEnter the name of the product:\n");
      out.write("\t<br>\n");
      out.write("\t <select class=\"form-control\" name =\"DailyProductName\">\n");
      out.write("\t \n");
      out.write("\t \t<option value=\"-1\">Select Product</option>\n");
      out.write("\t \t\n");
      out.write("\t \t");

			try{ 
				
				String sql ="SELECT * FROM product";

				resultSet = statement.executeQuery(sql);
		
 
				while(resultSet.next()){
		
      out.write("\n");
      out.write("\t\t\t<option>");
      out.print(resultSet.getString(2) );
      out.write("</option>\n");
      out.write("    \t");
 
		}

		} catch (Exception e) {
			e.printStackTrace();
		}
		
      out.write("\n");
      out.write("\t\n");
      out.write("\t </select>\n");
      out.write("\t<br>\n");
      out.write("\t\n");
      out.write("\tEnter the today's date:<br>\n");
      out.write("\t <input  class=\"form-control\" type=\"date\" name=\"DailyDate\" placeholder=\"eg:2018.09.09\" required> <br>\n");
      out.write("\t<br>\n");
      out.write("\n");
      out.write("\tEnter the buying price of the product:\n");
      out.write("\t<br>\n");
      out.write("\t<input  class=\"form-control\" type=\"number\" name=\"buyingPrice\" placeholder=\"eg:200.00\" min=\"1\" required> <br>\n");
      out.write("\t<br>\n");
      out.write("\n");
      out.write("\tEnter the selling price of the product:\n");
      out.write("\t<br>\n");
      out.write("\t<input  class=\"form-control\" type=\"number\" name=\"sellingPrice\" placeholder=\"eg:200.00\" min=\"1\"required> \n");
      out.write("\t<br>\n");
      out.write("    <br>\n");
      out.write("\t\n");
      out.write("\t<input type=\"submit\" class=\"btn btn-info btn-lg form-control\" value=\"Submit\">\n");
      out.write("\t<br>\n");
      out.write("\t</form>\n");
      out.write(" </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<!-- Modal ends here here -->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	try{ 
		
		String sql ="SELECT * FROM DailyPrice";

		resultSet = statement.executeQuery(sql);

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!-- Listing the results starts here -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("<div class=\"container\">\n");
      out.write("  <h2>List of markets and details which are added are given below:</h2>\n");
      out.write("  <p>The list of markets and the buying and selling prices can be changed here.</p>            \n");
      out.write("  <table class=\"table table-hover \"   >\n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("       <th>DP ID</th>\n");
      out.write("        <th>Market Name </th>\n");
      out.write("        <th>Product</th>\n");
      out.write("        <th>Date</th>\n");
      out.write("        <th>Buying Price</th>\n");
      out.write("        <th>Selling Price</th>\n");
      out.write("        <th> Activity 1 </th>\n");
      out.write("        <th> Activity 2  </th>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("    \n");
      out.write("\n");
 
 
while(resultSet.next()){

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("      <tr>\n");
      out.write("      \t <td>");
      out.print(resultSet.getString(1) );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(resultSet.getString(2) );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(resultSet.getString(3) );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(resultSet.getString(4) );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(resultSet.getString(5) );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(resultSet.getString(6) );
      out.write("</td>\n");
      out.write("       \t<td><button type=\"button\" class=\"btn btn-success\"><a href=\"UpdateDailyPriceForm.jsp?DPID=");
      out.print(resultSet.getString("DPID"));
      out.write(" \"class=\"submit1\">UPDATE</a></button></td>\n");
      out.write("        <td><button type=\"button\" class=\"btn btn-danger\"><a href = 'DeleteDailyPrice.jsp?d=");
      out.print(resultSet.getString("DPID"));
      out.write(" 'class=\"button1\">Delete</button></td>\n");
      out.write("      </tr>\n");
      out.write("    \n");
      out.write(" \n");
      out.write("</div>\n");
      out.write("\n");
 
}

} catch (Exception e) {
e.printStackTrace();
}

      out.write("\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("<footer class=\"w3-center w3-black w3-padding-16\">\n");
      out.write("  <p>Powered by <a href=\"https://www.w3schools.com/w3css/default.asp\" title=\"W3.CSS\" target=\"_blank\" class=\"w3-hover-text-green\">Agro web</a></p>\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
