/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-03 08:53:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<title>Homepage</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar (sit on top) -->\r\n");
      out.write("<div class=\"w3-top\">\r\n");
      out.write("  <div class=\"w3-bar w3-black w3-wide w3-padding w3-card\">\r\n");
      out.write("    <a href=\"#home\" class=\"w3-bar-item w3-button\"><b>AG</b> Agro</a>\r\n");
      out.write("    <!-- Float links to the right. Hide them on small screens -->\r\n");
      out.write("    <div class=\"w3-right w3-hide-small\">\r\n");
      out.write("      <a href=\"#products\" class=\"w3-bar-item w3-button\">Products</a>\r\n");
      out.write("      <a href=\"#about\" class=\"w3-bar-item w3-button\">About</a>\r\n");
      out.write("      <a href=\"#slideshow\" class=\"w3-bar-item w3-button\">Contact</a>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header class=\"w3-display-container w3-content w3-wide\" style=\"max-width:1500px;\" id=\"home\">\r\n");
      out.write("  <img class=\"w3-image\" src=\"img/22.jpg\" alt=\"bowl\" width=\"1500 !important\" height=\"500\">\r\n");
      out.write("  <div class=\"w3-display-middle w3-margin-top w3-center\">\r\n");
      out.write("    <h1 class=\"w3-xxlarge w3-text-white\"><span class=\"w3-padding w3-black w3-opacity-min\"><b>AG</b></span> <span class=\"w3-hide-small w3-text-black\">Agro</span></h1>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Page content -->\r\n");
      out.write("<div class=\"w3-content w3-padding\" style=\"max-width:1564px\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  <!-- About Section \r\n");
      out.write("  <div class=\"w3-container w3-padding-32\" id=\"about\">\r\n");
      out.write("    <h3 class=\"w3-border-bottom w3-border-light-grey w3-padding-16\">About Us</h3>\r\n");
      out.write("    <p> This is website created to help the farmers in  </p>\r\n");
      out.write("  </div>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row w3-padding-64\" id=\"about\">\r\n");
      out.write("    <div class=\"w3-col m6 w3-padding-large w3-hide-small\">\r\n");
      out.write("     <img src=\"img/heart.jpg\" class=\"w3-round w3-image w3-opacity-min\" alt=\"heart\" width=\"600\" height=\"750\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-col m6 w3-padding-large\">\r\n");
      out.write("      <h1 class=\"w3-center\">About Us</h1><br>\r\n");
      out.write("      <p class=\"w3-large\"> </p>\r\n");
      out.write("      <p class=\"w3-large w3-text-grey w3-hide-medium\">This website was created in order to help the farmers who are hardworking for our \r\n");
      out.write("      survival but still underated due to lack of popularity and identity.We people must learn to appreciate their work. so inorder\r\n");
      out.write("      help them we have created this website.through our website everybody can get information about crops, the ways of cultivating, \r\n");
      out.write("      the ways of maintaining it and the time of harvesting the plant. In our website viewers can view the product details, farmers details,\r\n");
      out.write("      details of farmers union, and daily price details. \r\n");
      out.write("       </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <hr>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("<div class=\"w3-center w3-padding-64\" id=\"products\">\r\n");
      out.write("      <span class=\"w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16\">El-contenido</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"w3-container w3-padding-32\" id=\"services\">\r\n");
      out.write("  <div class=\"w3-row-padding \">\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/bell.png\" alt=\"vegetebles\" style=\"width:100%\">\r\n");
      out.write("      <h3>Products</h3>\r\n");
      out.write("      <p>Variety of products with divided according to the nature of the products for a clear view. </p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\"><a href=\"UserProductUI.jsp\">View</a></button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/ava.jpg\" alt=\"farmer\" style=\"width:100%\">\r\n");
      out.write("      <h3>Farmers Products</h3>\r\n");
      out.write("      <p>FArmers product are kept</p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\"><a href=\"home.jsp\">View</a></button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/farmer.jpg\" alt=\"Mike\" style=\"width:100%\">\r\n");
      out.write("      <h3>Farmers Guide</h3>\r\n");
      out.write("      <p>Guiding viewer with proper details about harvest and planting. This page will give clear detail about each plant from the begining to the end</p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\"><a href=\"search.jsp\">View</a></button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/price.jpg\" alt=\"Dan\" style=\"width:100%\">\r\n");
      out.write("      <h3>Daily Price</h3>\r\n");
      out.write("      <p>Updating the daily price according to the daily market6 price. This page will update every morning based on the market prices.</p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\"><a href=\"UserDailyPriceHome.jsp\">View</a></button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/water.jpg\" alt=\"John\" style=\"width:100%\">\r\n");
      out.write("      <h3>Cost Guide</h3>\r\n");
      out.write("      <p>This page provides the details about the amount of money spent for cultivating, harvesting and price of seeds for a plant. </p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\"><a href=\"userCostGuide.jsp\">View</a></button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/uni.png\" alt=\"Jane\" style=\"width:100%\">\r\n");
      out.write("      <h3>Farmers Union</h3>\r\n");
      out.write("      <p>This section contains details about the farmers union and their functions and also the union leaders details.</p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\"><a href=\"unionuser.jsp\">View</a></button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/hat.jpg\" alt=\"Mike\" style=\"width:100%\">\r\n");
      out.write("      <h3>farmer Profile</h3>\r\n");
      out.write("      <p>The farmers details are visible and the the crop grown by them are stored in this page.</p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\">View</button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-margin-bottom\">\r\n");
      out.write("      <img src=\"img/mark.jpeg\" alt=\"Dan\" style=\"width:100%\">\r\n");
      out.write("      <h3>Market</h3>\r\n");
      out.write("      <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>\r\n");
      out.write("      <p><button class=\"w3-button w3-light-grey w3-block\"><a href=\"MarketUserUI.jsp\">View</a></button></p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"mySlides w3-display-container w3-center\" id=\"slideshow\">\r\n");
      out.write("    <img src=\"img/oni.jpg\" style=\"width:100%\">\r\n");
      out.write("    <div class=\"w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small\">\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mySlides w3-display-container w3-center\">\r\n");
      out.write("    <img src=\"img/app.jpg\" style=\"width:100%\">\r\n");
      out.write("    <div class=\"w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small\">\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mySlides w3-display-container w3-center\">\r\n");
      out.write("    <img src=\"img/carr.jpg\" style=\"width:100%\">\r\n");
      out.write("    <div class=\"w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small\">\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"w3-center w3-black w3-padding-16\">\r\n");
      out.write("  <p>Powered by <a href=\"https://www.w3schools.com/w3css/default.asp\" title=\"W3.CSS\" target=\"_blank\" class=\"w3-hover-text-green\">Agro web</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Automatic Slideshow - change image every 4 seconds\r\n");
      out.write("var myIndex = 0;\r\n");
      out.write("carousel();\r\n");
      out.write("\r\n");
      out.write("function carousel() {\r\n");
      out.write("  var i;\r\n");
      out.write("  var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("  for (i = 0; i < x.length; i++) {\r\n");
      out.write("    x[i].style.display = \"none\";  \r\n");
      out.write("  }\r\n");
      out.write("  myIndex++;\r\n");
      out.write("  if (myIndex > x.length) {myIndex = 1}    \r\n");
      out.write("  x[myIndex-1].style.display = \"block\";  \r\n");
      out.write("  setTimeout(carousel,2000 );    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Used to toggle the menu on small screens when clicking on the menu button\r\n");
      out.write("function myFunction() {\r\n");
      out.write("  var x = document.getElementById(\"navDemo\");\r\n");
      out.write("  if (x.className.indexOf(\"w3-show\") == -1) {\r\n");
      out.write("    x.className += \" w3-show\";\r\n");
      out.write("  } else { \r\n");
      out.write("    x.className = x.className.replace(\" w3-show\", \"\");\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("var modal = document.getElementById('ticketModal');\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("  if (event.target == modal) {\r\n");
      out.write("    modal.style.display = \"none\";\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
