/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-05 05:47:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Utility.DBConnection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class ReportMarket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("Utility.DBConnection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/DailyPriceSearchCss.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Search Daily Price</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("\n");
      out.write("body{\n");
      out.write("\tbackground-image:url(img/bb.jpg);\t\n");
      out.write("}\n");
      out.write("\n");
      out.write(".canvas_div_pdf{\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"row pt-1 pb-1\">\n");
      out.write("        <div class=\"col-lg-12\">\n");
      out.write("            <h4 class=\"text-center\">Daily Vegetable Price Report</h4>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<section>\n");
      out.write("    <div id=\"carouselExampleFade\" class=\"carousel slide carousel-fade\" data-ride=\"carousel\">\n");
      out.write("        <div class=\"carousel-inner\">\n");
      out.write("          \n");
      out.write("            \n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#carouselExampleFade\" role=\"button\" data-slide=\"prev\">\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("            <span class=\"sr-only\">Previous</span>\n");
      out.write("        </a>\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#carouselExampleFade\" role=\"button\" data-slide=\"next\">\n");
      out.write("            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("            <span class=\"sr-only\">Next</span>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"search-sec\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <form action=\"\" method=\"get\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-9 col-md-9 col-sm-12 p-0\">\n");
      out.write("                            <input type=\"text\" class=\"form-control search-slt\" placeholder=\"Enter Product Name\" name=\"search\" required>\n");
      out.write("                        </div>\n");
      out.write("                      \n");
      out.write("                        <div class=\"col-lg-3 col-md-3 col-sm-12 p-0\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-danger wrn-btn\"><i class=\"fa fa-search\">Search</i></button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");

	String id = request.getParameter("userID");
	DBConnection db = new DBConnection();


	Connection con = db.createConnection();
	Statement statement = con.createStatement();
	ResultSet resultSet = null;

      out.write('\n');
      out.write('\n');

try{ 
	
	String Search = request.getParameter("search");
	String sql ="SELECT * FROM DailyPrice where ProductName = '"+request.getParameter("search")+"'";

	resultSet = statement.executeQuery(sql);
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("    <div class=\"canvas_div_pdf\">\n");
      out.write("\t<button id=\"cmd\" onClick=\"getPDF()\" class=\"btn btn-primary active\">generate PDF</button>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("    \n");
      out.write(" <div class=\"\">\n");
      out.write("  <h1 class=\"text-center\">VEGETABLE REPORT</h1>      \n");
      out.write("  <p>Vegetable Name:");
      out.print(request.getParameter("search"));
      out.write("</p>  \n");
      out.write("</div>            \n");
      out.write("  <table class=\"table table-striped\">\n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("        <th>Market Name</th>\n");
      out.write("        <th>Buying Price</th>\n");
      out.write("        <th>Selling Price</th>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("   \n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t");
 
	
	 
	while(resultSet.next()){
	
      out.write("\n");
      out.write("\t\n");
      out.write("\t<tbody>\n");
      out.write("      <tr>\n");
      out.write("        <td>");
      out.print(resultSet.getString(2) );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(resultSet.getString(5) );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(resultSet.getString(6) );
      out.write("</td>\n");
      out.write("      </tr>\n");
      out.write("     \n");
      out.write("    </tbody>\n");
      out.write("\t\n");
      out.write("\t\t\t\n");
      out.write("\t\n");
      out.write("\t\t\t\n");
      out.write("\t       \t\t\n");
      out.write("\t       \t\t \n");
      out.write("\t       \t\t \n");
      out.write("\t        ");
 
	}

	} catch (Exception e) {
	e.printStackTrace();
	}
	
      out.write("\n");
      out.write("\t\n");
      out.write("\t  </table>\n");
      out.write("</div>\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t</div>   \n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\t\n");
      out.write("\tfunction getPDF(){\n");
      out.write("\t\t \n");
      out.write("\t\tvar HTML_Width = $(\".canvas_div_pdf\").width();\n");
      out.write("\t\tvar HTML_Height = $(\".canvas_div_pdf\").height();\n");
      out.write("\t\tvar top_left_margin = 15;\n");
      out.write("\t\tvar PDF_Width = HTML_Width+(top_left_margin*2);\n");
      out.write("\t\tvar PDF_Height = (PDF_Width*1.5)+(top_left_margin*2);\n");
      out.write("\t\tvar canvas_image_width = HTML_Width;\n");
      out.write("\t\tvar canvas_image_height = HTML_Height;\n");
      out.write("\t\t\n");
      out.write("\t\tvar totalPDFPages = Math.ceil(HTML_Height/PDF_Height)-1;\n");
      out.write("\t\t\n");
      out.write("\t\t$(document).ready(function(){\n");
      out.write("\t\t    $(\"#cmd\").hide();\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\thtml2canvas($(\".canvas_div_pdf\")[0],{allowTaint:true}).then(function(canvas) {\n");
      out.write("\t\t\tcanvas.getContext('2d');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tconsole.log(canvas.height+\"  \"+canvas.width);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar imgData = canvas.toDataURL(\"image/jpeg\", 1.0);\n");
      out.write("\t\t\tvar pdf = new jsPDF('p', 'pt',  [PDF_Width, PDF_Height]);\n");
      out.write("\t\t    pdf.addImage(imgData, 'JPG', top_left_margin, top_left_margin,canvas_image_width,canvas_image_height);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfor (var i = 1; i <= totalPDFPages; i++) { \n");
      out.write("\t\t\t\tpdf.addPage(PDF_Width, PDF_Height);\n");
      out.write("\t\t\t\tpdf.addImage(imgData, 'JPG', top_left_margin, -(PDF_Height*i)+(top_left_margin*4),canvas_image_width,canvas_image_height);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t    pdf.save(\"PriceSummary.pdf\");\n");
      out.write("\t    });\n");
      out.write("\t\t\n");
      out.write("\t\t$(document).ready(function(){\n");
      out.write("\t\t    $(\"#cmd\").showq1();\n");
      out.write("\t\t});\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t</script>    \n");
      out.write("\t\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.3/jspdf.min.js\"></script>\n");
      out.write("\t<script src=\"https://html2canvas.hertzen.com/dist/html2canvas.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
